name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, windows-2019]
        gcc: [9, 10, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Download precompiled z++.exe
        run: |
          $url = "https://gh-proxy.com/github.com/Eternity-Sky/ZPP/blob/main/bin/z%2B%2B.exe"
          try {
            Invoke-WebRequest -Uri $url -OutFile "bin\z++.exe" -ErrorAction Stop
            if (!(Test-Path "bin\z++.exe")) {
              Write-Host "错误: 文件下载成功但未找到"
              exit 1
            }
          } catch {
            Write-Host "错误: 下载失败 - $_"
            exit 1
          }
      - uses: actions/checkout@v3
      - name: Set up g++
        run: choco install mingw -y
      - name: Compile Z++
        run: bin\cmp.bat
      - name: Run tests
        run: bin\z++.exe exp\main.zpp
      - uses: actions/checkout@v3
      - name: Set up g++
        run: choco install mingw -y
      - name: Compile Z++
        run: bin\cmp.bat
      - name: Run tests
        run: bin\z++.exe exp\main.zpp