            - name: cpp-lint-action
  # You may pin to the exact commit or the version.
  # uses: emmett2020/cpp-lint-action@362ea233f33230d5603339199053e1d65f1db50b
  uses: emmett2020/cpp-lint-action@v1.0.0
  with:
    # Set the log verbose level of cpp-lint-action.
Supports: [trace, debug, info, error]

    log-level: # optional, default is info
    # Set the target revision of git repository. It usually is the default branch
you want to be merged into. If you omit this option, cpp-lint-action will
automatically detect this.

    target-revision: # optional
    # Whether enable comment on Github issues
    enable-comment-on-issue: # optional, default is true
    # Whether enable Github pull-request review comment
    enable-pull-request-review: # optional
    # Whether enable write step summary to Github action
    enable-step-summary: # optional, default is true
    # Whether enable write output to Github action
    enable-action-output: # optional, default is true
    # Whether disable errors. If errors are disabled, this action will not be failed.
You can use this action's output to customize later behavior.

    disable-errors: # optional
    # Enable clang-format check
    enable-clang-format: # optional, default is true
    # Enabel clang-format fastly exit. This means
cpp-lint-action will stop clang-format as soon
as first file error occurs

    enable-clang-format-fastly-exit: # optional
    # Set the version of clang-format. Don't specify
both this option and the clang-format-binary option
to avoid ambigous. And the clang-format-${version} must
exist in your $PATH

    clang-format-version: # optional
    # Set the full path of clang-format executable binary.
Don't spefify both this option and the clang-format-version
option to avoid ambigous

    clang-format-binary: # optional
    # Set the source file filter for clang-format.
    clang-format-file-iregex: # optional
    # Enable clang-tidy check
    enable-clang-tidy: # optional, default is true
    # Enabel clang-tidy fastly exit. This means
cpp-lint-action will stop clang-tidy as soon
as first file error occurs

    enable-clang-tidy-fastly-exit: # optional
    # Set the version of clang-tidy. Don't specify
both this option and the clang-tidy-binary option
to avoid ambigous. And the clang-tidy-${version} must
exist in your $PATH

    clang-tidy-version: # optional
    # Set the full path of clang-tidy executable binary.
Don't spefify both this option and the clang-tidy-version
option to avoid ambigous

    clang-tidy-binary: # optional
    # Set the source file filter for clang-tidy.
    clang-tidy-file-iregex: # optional
    # Same as clang-tidy -p option
    clang-tidy-database: # optional
    # Enabel clang-tidy allow_no_check option
    clang-tidy-allow-no-checks: # optional
    # Enabel clang-tidy enable_check_profile option
    clang-tidy-enable-check-profile: # optional
    # Same as clang-tidy checks option
    clang-tidy-checks: # optional
    # Same as clang-tidy config option
    clang-tidy-config: # optional
    # Same as clang-tidy config-file option
    clang-tidy-config-file: # optional
    # Same as clang-tidy header-filter option
    clang-tidy-header-filter: # optional
    # Same as clang-tidy line-filter option
    clang-tidy-line-filter: # optional
          
